services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: copluk-server
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./server:/app
    depends_on:
      - mongo
    env_file:
      - ./server/.env
    
  mongo:
    image: mongo:latest
    container_name: copluk-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongo-data: