services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: copluk-server
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./server:/app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: copluk-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongo-data:
